"""empty message

Revision ID: 4acb45306fb6
Revises: 829a0abf1761
Create Date: 2019-04-11 22:27:14.939953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acb45306fb6'
down_revision = '829a0abf1761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'time')
    # ### end Alembic commands ###
