"""empty message

Revision ID: 829a0abf1761
Revises: cbe19653b8cf
Create Date: 2019-04-11 22:00:18.629270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829a0abf1761'
down_revision = 'cbe19653b8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('superlikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'superlikes')
    # ### end Alembic commands ###
