"""empty message

Revision ID: e3638c9486b8
Revises: 945e0cb3c6e0
Create Date: 2019-04-11 16:12:16.915675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3638c9486b8'
down_revision = '945e0cb3c6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updates', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('updates', 'likes')
    # ### end Alembic commands ###
